import type { SubstrateDef, PlantDef, FaunaDef } from "./types";

export const SUBSTRATES: SubstrateDef[] = [
  {
    id: "coir",
    name: "Coco Coir",
    retention: 0.9,
    fertility: 0.5,
    acidity: 0.4,
    color: "#6b3a1f",
    blurb: "Holds water like a sponge. Plants love it; mold loves it more.",
  },
  {
    id: "loam",
    name: "Forest Loam",
    retention: 0.6,
    fertility: 0.9,
    acidity: 0.5,
    color: "#4a2a14",
    blurb: "Balanced and nutrient-rich. The safe pick.",
  },
  {
    id: "sandy",
    name: "Sandy Mix",
    retention: 0.25,
    fertility: 0.3,
    acidity: 0.4,
    color: "#a98a55",
    blurb: "Drains fast. Only the hardiest survive.",
  },
  {
    id: "sphagnum",
    name: "Sphagnum Base",
    retention: 0.95,
    fertility: 0.4,
    acidity: 0.85,
    color: "#7a6b3c",
    blurb: "Very damp and acidic. Moss heaven.",
  },
];

export const PLANTS: PlantDef[] = [
  {
    id: "fern",
    name: "Fern",
    moistureMin: 55,
    moistureMax: 90,
    lightMin: 6,
    growth: 0.6,
    nutrientUse: 0.4,
    edibleValue: 25,
    color: "#2f6b32",
    accent: "#6ab04c",
    blurb: "Loves humidity, hates drought.",
  },
  {
    id: "moss",
    name: "Cushion Moss",
    moistureMin: 65,
    moistureMax: 100,
    lightMin: 3,
    growth: 0.35,
    nutrientUse: 0.15,
    edibleValue: 15,
    color: "#4d8b3a",
    accent: "#94c267",
    blurb: "Thrives in damp, dim corners.",
  },
  {
    id: "pilea",
    name: "Pilea",
    moistureMin: 40,
    moistureMax: 75,
    lightMin: 8,
    growth: 0.55,
    nutrientUse: 0.5,
    edibleValue: 30,
    color: "#3a7d44",
    accent: "#a3d977",
    blurb: "Bright light, moderate water.",
  },
  {
    id: "lichen",
    name: "Lichen",
    moistureMin: 25,
    moistureMax: 80,
    lightMin: 4,
    growth: 0.2,
    nutrientUse: 0.05,
    edibleValue: 8,
    color: "#9aa66b",
    accent: "#c7d290",
    blurb: "Tough little survivor.",
  },
  {
    id: "orchid",
    name: "Tiny Orchid",
    moistureMin: 50,
    moistureMax: 70,
    lightMin: 10,
    growth: 0.45,
    nutrientUse: 0.6,
    edibleValue: 35,
    color: "#a85a8a",
    accent: "#f5b8d9",
    blurb: "Picky, but stunning when happy.",
  },
];

export const FAUNA: FaunaDef[] = [
  {
    id: "springtail",
    name: "Springtails",
    diet: "mold",
    hungerRate: 0.4,
    humidityMin: 50,
    humidityMax: 100,
    reproduceAt: 80,
    color: "#e8e6d8",
    blurb: "Eat mold. The cleanup crew.",
  },
  {
    id: "isopod",
    name: "Isopods",
    diet: "decay",
    hungerRate: 0.5,
    humidityMin: 55,
    humidityMax: 95,
    reproduceAt: 85,
    color: "#7a6552",
    blurb: "Pill bugs that recycle dead matter into nutrients.",
  },
  {
    id: "snail",
    name: "Snail",
    diet: "plant",
    hungerRate: 0.7,
    humidityMin: 60,
    humidityMax: 100,
    reproduceAt: 90,
    color: "#c2a878",
    blurb: "Eats your live plants. High risk.",
  },
  {
    id: "ant",
    name: "Ants",
    diet: "omnivore",
    hungerRate: 0.6,
    humidityMin: 35,
    humidityMax: 75,
    reproduceAt: 85,
    color: "#3a2418",
    blurb: "Industrious omnivores. Will eat small fauna.",
  },
];

export const substrateById = (id: string) =>
  SUBSTRATES.find((s) => s.id === id)!;
export const plantById = (id: string) => PLANTS.find((p) => p.id === id)!;
export const faunaById = (id: string) => FAUNA.find((f) => f.id === id)!;